"""Domain models — plain dataclasses with no framework dependencies.

These are the vocabulary the rest of the application speaks.  Nothing in this
module imports FastAPI, LangGraph or LangChain, which is what keeps the agent
and service layers portable and unit-testable.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any, Literal

Role = Literal["user", "assistant", "system"]


class StreamChannel(StrEnum):
    """Which of the two streaming surfaces produced an envelope."""

    #: ``graph.astream(...)`` — the LangGraph state stream (values/updates/...).
    GRAPH = "graph"
    #: ``graph.astream_events(...)`` — the callback event taxonomy (v2).
    EVENTS = "events"
    #: Envelopes generated by this application, not by LangGraph.
    CONTROL = "control"


class ControlEvent(StrEnum):
    """Lifecycle markers this application injects around a run."""

    STREAM_START = "stream.start"
    STREAM_END = "stream.end"
    STREAM_ERROR = "stream.error"


@dataclass(slots=True, frozen=True)
class ChatMessage:
    """One turn of conversation, provider agnostic."""

    role: Role
    content: str


@dataclass(slots=True, frozen=True)
class MCPServerSpec:
    """Connection details for a single MCP server."""

    name: str
    url: str | None
    transport: str = "streamable_http"
    headers: dict[str, str] = field(default_factory=dict)
    extra: dict[str, Any] = field(default_factory=dict)

    def to_connection(self) -> dict[str, Any]:
        """Render the mapping ``MultiServerMCPClient`` expects."""
        connection: dict[str, Any] = {"transport": self.transport, **self.extra}
        if self.url is not None:
            connection["url"] = self.url
        if self.headers:
            connection["headers"] = self.headers
        return connection


@dataclass(slots=True, frozen=True)
class AgentSpec:
    """Declarative definition of a ReAct worker agent.

    Agents are data, not code: adding a fourth worker means appending one of
    these, never touching the factory, the supervisor or the API.
    """

    name: str
    title: str
    description: str
    prompt: str
    #: Names of MCP servers whose tools this agent may call.
    mcp_servers: tuple[str, ...] = ()
    #: Optional model override; falls back to the configured default.
    model: str | None = None
    #: Optional provider override — e.g. run one worker on a local Ollama model
    #: while the rest use the configured default.
    provider: str | None = None

    @property
    def handoff_description(self) -> str:
        """One-liner the supervisor sees when choosing a delegate."""
        return f"{self.title}: {self.description}"


@dataclass(slots=True, frozen=True)
class AgentInfo:
    """Runtime view of an agent, including what MCP actually yielded."""

    name: str
    title: str
    description: str
    mcp_servers: tuple[str, ...]
    tools: tuple[str, ...]
    model: str
    provider: str


@dataclass(slots=True, frozen=True)
class MCPServerStatus:
    """Health/readiness of one configured MCP server."""

    name: str
    configured: bool
    connected: bool
    transport: str
    tool_count: int = 0
    error: str | None = None


@dataclass(slots=True)
class RunRequest:
    """A single execution request against the supervisor graph."""

    messages: list[ChatMessage]
    thread_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    recursion_limit: int | None = None
    stream_modes: list[str] | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_graph_input(self) -> dict[str, Any]:
        return {
            "messages": [
                {"role": message.role, "content": message.content}
                for message in self.messages
            ]
        }


@dataclass(slots=True, frozen=True)
class StreamEnvelope:
    """Uniform wrapper around every chunk emitted to a client.

    Both streaming surfaces are normalised into this shape so a consumer can
    write one parser instead of two.
    """

    seq: int
    channel: StreamChannel
    event: str
    payload: Any
    thread_id: str
    namespace: tuple[str, ...] = ()
    ts: float = field(default_factory=time.time)

    def to_dict(self) -> dict[str, Any]:
        return {
            "seq": self.seq,
            "channel": self.channel.value,
            "event": self.event,
            "namespace": list(self.namespace),
            "thread_id": self.thread_id,
            "ts": self.ts,
            "payload": self.payload,
        }
